self hosted runner is introuced in github for this project so that ci/cd can access the local machine instead of using git hub virtual machine

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,7 +10,7 @@ on:
 
 jobs:
   build-and-test:
-    runs-on: ubuntu-latest
+    runs-on: self-hosted
 
     steps:
       # Step 1: Checkout code
@@ -31,7 +31,7 @@ jobs:
 
       - name: Debug Files Before Upload
         run: |
-          ls -R :/Users/Tim/Desktop/ISRAT/RostockUniversity/PyCharmProjects/ || echo "Directory not found!"
+          ls -R ${{ github.workspace }} || echo "Directory not found!"
 
 
       # Step 4: Upload DVC Storage as Artifact from local machine
@@ -39,7 +39,7 @@ jobs:
         uses: actions/upload-artifact@v3
         with:
           name: dvc-storage
-          path: C:/Users/Tim/Desktop/ISRAT/RostockUniversity/PyCharmProjects/
+          path: ${{ github.workspace }}/data/
 
       # Step 5: Run linting (optional)
       - name: Run Linting
@@ -56,7 +56,7 @@ jobs:
         uses: actions/download-artifact@v3
         with:
           name: dvc-storage
-          path: C:/Users/Tim/Desktop/ISRAT/RostockUniversity/PyCharmProjects/
+          path: ${{ github.workspace }}/data/
 
       # Step 8: Pull DVC data
       - name: Pull DVC Data
@@ -66,13 +66,13 @@ jobs:
       # Step 9: Debug Files (optional)
       - name: Debug Files
         run: |
-          ls -R
+          ls -R ${{ github.workspace }}
 
       # Step 10: Run tests
       - name: Run Tests
         run: |
           pip install pytest
-          pytest -s tests/test_script.py
+          pytest -s tests/
 
       # Step 11: Execute script
       - name: Run Script
